default: all
doc:
	latex problemstatement.tex
	dvips problemstatement.dvi
	ps2pdf problemstatement.ps
all: doc clean
clean:
	rm -f *.o *.exe
	rm -f problemstatement.aux
	rm -f problemstatement.dvi
	rm -f problemstatement.log
	rm -f problemstatement.out
	rm -f problemstatement.ps
